[versions]
agp = "8.7.3"
androidx-lifecycle = "2.8.3"
composeWebviewMultiplatform = "1.9.20"
epublibCore = "3.1"
filekitCompose = "0.8.7"
jsoup = "1.18.1"
kotlin = "2.0.21"
kotlinx-coroutines = "1.9.0"
kotlinxSerializationJson = "1.7.3"
kxml2 = "2.3.0"
multiplatformSettings = "1.2.0"
orbitCore = "9.0.0"
pixko = "1.9"
room = "2.7.0-alpha11"
sketchCompose = "4.0.0-alpha08"
sqliteBundled = "2.5.0-alpha11"
voyagerVersion = "1.1.0-beta03"
ksp = "2.0.21-1.0.26"
aboutlibraries = "11.2.3"
zoomimageComposeSketch = "1.1.0-beta01"
compose-settings = "2.6.0"

[libraries]
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.3" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqliteBundled" }
compose-webview-multiplatform = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "composeWebviewMultiplatform" }
epublib-core = { module = "com.positiondev.epublib:epublib-core", version.ref = "epublibCore"}
filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "filekitCompose" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.6.1" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kxml2 = { module = "net.sf.kxml:kxml2", version.ref = "kxml2" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatform-settings-serialization = { module = "com.russhwolf:multiplatform-settings-serialization", version.ref = "multiplatformSettings" }
orbit-core = { module = "org.orbit-mvi:orbit-core", version.ref = "orbitCore" }
pixko = { module = "top.kagg886:pixko", version.ref = "pixko" }
sketch-extensions-compose = { module = "io.github.panpf.sketch4:sketch-extensions-compose", version.ref = "sketchCompose" }
sketch-compose = { module = "io.github.panpf.sketch4:sketch-compose", version.ref = "sketchCompose" }
sketch-http-okhttp = { module = "io.github.panpf.sketch4:sketch-http-okhttp", version.ref = "sketchCompose" }
voyager-bottom-sheet-navigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyagerVersion" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyagerVersion" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyagerVersion" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyagerVersion" }
koin-core = { group = "io.insert-koin", name = "koin-core", version = "4.0.0" }
zoomimage-compose-sketch = { module = "io.github.panpf.zoomimage:zoomimage-compose-sketch", version.ref = "zoomimageComposeSketch" }
compose-settings-ui = { group = "com.github.alorma.compose-settings", name = "ui-tiles", version.ref = "compose-settings" }
compose-settings-extended = { group = "com.github.alorma.compose-settings", name = "ui-tiles-extended", version.ref = "compose-settings" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version = "1.7.0" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.5.0" }
ksp = { id = 'com.google.devtools.ksp', version.ref = 'ksp' }
room = { id = "androidx.room", version.ref = "room" }
aboutlibrariesPlugin = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }