name: macos build test
on:
  push:
    branches: [ "dev-macos" ]
jobs:
  build-macos:
    runs-on: macos-latest-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew packageReleaseDmg
        env:
          APP_VERSION_NAME: ${{ github.ref_name }}

      - name: Rename artifact
        run: |
          filename=$(ls composeApp/build/compose/binaries/main-release/dmg/)
          mv composeApp/build/compose/binaries/main-release/dmg/${filename} composeApp/build/compose/binaries/main-release/dmg/macos.dmg

      - name: Upload macos artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos.dmg
          path: composeApp\build\compose\binaries\main-release\dmg\macos.dmg